service:
  name: initiative-tracker

plugins:
  - serverless-plugin-epsagon
  - serverless-webpack
  - serverless-plugin-iam-checker
  - serverless-cloudformation-resource-counter

provider:
  name: aws
  stage: local
  runtime: nodejs8.10
  environment:
    INITIATIVES_TABLE: { Ref: InitiativesTable }
    REVISION: ${file(infrastructure/helper.js):revision}
    STAGE: ${opt:stage, self:provider.stage}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_REDIRECT_URI:
      Fn::Join:
        - ''
        - - 'https://'
          - { Ref: ApiGatewayRestApi }
          - '.execute-api.'
          - { Ref: AWS::Region }
          - '.'
          - { Ref: AWS::URLSuffix }
          - '/${opt:stage, self:provider.stage}/redirect'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: { Fn::GetAtt: [InitiativesTable, Arn] }

custom:
  epsagon:
    token: ${env:EPSAGON_TOKEN}
    appName: ${self:service.name}-${opt:stage, self:provider.stage}

functions:
  join-initiative:
    handler: app/join-initiative.handler
    events:
      - http:
          method: post
          path: initiatives/join

  say-hello:
    handler: app/say-hello.foo
    events:
      - http:
          method: post
          path: initiatives/say-hello

  create-initiative:
    handler: app/create-initiative.handler
    events:
      - http:
          method: post
          path: initiatives/create

  list-initiatives:
    handler: app/list-initiatives.handler
    events:
      - http:
          method: post
          path: initiatives/list

  action-endpoint:
    handler: app/action-endpoint.handler
    events:
      - http:
          method: post
          path: actions

  auth-redirect:
    handler: app/auth-redirect.handler
    events:
      - http:
          method: get
          path: /auth/redirect

resources:
  Resources:
    InitiativesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
        KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: sortKey
            KeySchema:
              - AttributeName: sortKey
                KeyType: HASH
            Projection:
              ProjectionType: ALL
