service:
  name: intiative-tracker

plugins:
  - serverless-plugin-iopipe
  - serverless-webpack
  - serverless-plugin-iam-checker
  - serverless-cloudformation-resource-counter
  - serverless-stack-output

provider:
  name: aws
  stage: local
  runtime: nodejs8.10
  environment:
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}

functions:
  hello:
    handler: app/hello.handler
    events:
      - http:
          method: get
          path: hello

  auth-redirect:
    handler: app/auth-redirect.handler
    events:
      - http:
          method: get
          path: /auth/redirect
