service:
  name: initiative-tracker

plugins:
  - serverless-plugin-epsagon
  - serverless-webpack
  - serverless-plugin-iam-checker
  - serverless-cloudformation-resource-counter

provider:
  name: aws
  stage: local
  runtime: nodejs8.10
  environment:
    INITIATIVES_TABLE: ${self:custom.initiativesTableName}
    REVISION: ${file(infrastructure/helper.js):revision}
    STAGE: ${opt:stage, self:provider.stage}
    REGION: ${self:custom.config.region}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_REDIRECT_URI:
      Fn::Join:
        - ''
        - - 'https://'
          - { Ref: ApiGatewayRestApi }
          - '.execute-api.'
          - { Ref: AWS::Region }
          - '.'
          - { Ref: AWS::URLSuffix }
          - '/${opt:stage, self:provider.stage}/redirect'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ InitiativesTable, Arn ]

custom:
  stage: ${opt:stage, self:provider.stage}
  initiativesTableName: ${self:custom.stage}-initiatives-2
  config: ${file(infrastructure/configurations.yml)}
  properties: ${file(infrastructure/properties.yml)}
  epsagon:
    token: ${env:EPSAGON_TOKEN}
    appName: ${self:service.name}-${opt:stage, self:provider.stage}

functions:
  register-initiative:
    handler: app/register-initiative.handler
    events:
      - http:
          method: post
          path: initiatives

  action-endpoint:
    handler: app/action-endpoint.handler
    events:
      - http:
          method: post
          path: actions

  auth-redirect:
    handler: app/auth-redirect.handler
    events:
      - http:
          method: get
          path: /auth/redirect


resources:
  - ${file(infrastructure/dynamodb-tables.yml)}