service:
  name: initiative-tracker

plugins:
  - serverless-plugin-iopipe
  - serverless-webpack
  - serverless-plugin-iam-checker
  - serverless-cloudformation-resource-counter
  - serverless-domain-manager

provider:
  name: aws
  stage: ${opt:stage, self:provider.stage, 'local'}
  runtime: nodejs8.10
  environment:
    IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    INITIATIVES_TABLE: { Ref: InitiativesTable }
    INITIATIVES_TABLE_TYPE_INDEX: ${self:custom.typeIndex}
    INITIATIVES_TABLE_STATUS_INDEX: ${self:custom.statusIndex}
    REQUEST_UPDATE_SNS:
      Fn::Join:
        - ':'
        - - arn:aws:sns
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - request-update-${self:provider.stage}
    REVISION: ${file(infrastructure/helper.js):revision}
    STAGE: ${self:provider.stage}
    SLACK_CLIENT_ID: ${env:${self:provider.stage}_SLACK_CLIENT_ID, env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:${self:provider.stage}_SLACK_CLIENT_SECRET, env:SLACK_CLIENT_SECRET}
    SLACK_SIGNING_SECRET: ${env:${self:provider.stage}_SLACK_SIGNING_SECRET, env:SLACK_SIGNING_SECRET}
    SLACK_ACCESS_TOKEN: ${env:${self:provider.stage}_SLACK_ACCESS_TOKEN, env:SLACK_ACCESS_TOKEN}
    SLACK_REDIRECT_URI: https://initiative.ninja/${self:provider.stage}/auth/redirect
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { Fn::GetAtt: [InitiativesTable, Arn] }
        - { Fn::Join: ['', [{ Fn::GetAtt: [InitiativesTable, Arn] }, '/index/*']] }
    - Effect: Allow
      Action: sns:Publish
      Resource:
        Fn::Join:
          - ':'
          - - arn:aws:sns
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - request-update-${self:provider.stage}

custom:
  typeIndex: TYPE_INDEX
  statusIndex: STATUS_INDEX
  customDomain:
    basePath: ${self:provider.stage}
    certificateName: initiative.ninja
    domainName: initiative.ninja

functions:
  initiate-update-request:
    handler: app/initiate-update-request.handler
    events:
      - schedule: cron(0 15 ? * MON *) # 3PM UTC (10 AM EST) every Monday
      - schedule: cron(0/5 * * * ? *) # every 5 minutes for testing

  request-update:
    handler: app/request-update.handler
    events:
      - sns: request-update-${self:provider.stage}

  add-initiative:
    handler: app/add-initiative.handler
    events:
      - http:
          method: post
          path: add

  list-initiatives:
    handler: app/list-initiatives.handler
    events:
      - http:
          method: post
          path: list

  action-endpoint:
    handler: app/action-endpoint.handler
    events:
      - http:
          method: post
          path: actions

  auth-redirect:
    handler: app/auth-redirect.handler
    events:
      - http:
          method: get
          path: /auth/redirect

resources:
  Resources:
    InitiativesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: initiativeId
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: initiativeId
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.typeIndex}
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: initiativeId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:custom.statusIndex}
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: status
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
