service:
  name: intiative-tracker

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: local
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
