Resources:
  InitiativesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.initiativesTableName}
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: sortKey
          KeySchema:
            - AttributeName: sortKey
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.config.table.min}
            WriteCapacityUnits: ${self:custom.config.table.min}      
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.config.table.min}
        WriteCapacityUnits: ${self:custom.config.table.min}