Resources:
  InitiativesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.initiativesTableName}
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: creator
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: creator
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.config.table.min}
        WriteCapacityUnits: ${self:custom.config.table.min}